base my_project
setting __init__.py,dev.py,prod.py
mainapp __init__.py,model.py,views.py
mainapp/templates/mainapp base.html,index.html
authapp __init__.py,models.py,views.py
authapp/templates/authapp base.html,index.html